Repository data-exp-lab/analysis_schema, pull requests merged in 2022-09, with the labels that each got.

#39 Run analysis to the full command line interface
  README.md
  analysis_schema/_workflows.py
  analysis_schema/cli.py
  analysis_schema/run_analysis.py
  tests/test_analysis_schema_cli.py
Labels: enhancement

#35 allow multiple fields, test improvements
  MANIFEST.in
  analysis_schema/_model_instantiation.py
  analysis_schema/_testing.py
  analysis_schema/data_classes.py
  analysis_schema/pydantic_schema_example.json
  analysis_schema/yt_analysis_schema.json
  tests/test_visualizations.py
  tests/test_workflows.py
  tests/test_ytschema.py
  tests/viz_multi_fields.json
  tests/viz_projectionplot.json
  tests/viz_sliceplot.json
Labels: enhancement, testing

#40 'FileName' is not optional in the schema
  analysis_schema/_workflows.py
  analysis_schema/data_classes.py
  analysis_schema/pydantic_schema_example.json
  analysis_schema/yt_analysis_schema.json
Labels: bug

#38 Phaseplot fixes
  .github/workflows/build-test.yaml
  analysis_schema/_model_instantiation.py
  analysis_schema/_testing.py
  analysis_schema/data_classes.py
  analysis_schema/yt_analysis_schema.json
  tests/viz_phaseplot_1.json
  tests/viz_phaseplot_2.json
Labels: bug
